# This is a basic workflow to help you get started with Actions

name: Run on CREATE

# Controls when the workflow will run
on:
  create:  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Add .NETCore SDK latest stable
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        
      # Run dotnet new --install Umbraco.Templates
      - name: Install Umbraco dotnet new templates
        run: dotnet new --install Umbraco.Templates
        
      - name: Install Umbraco
        run: dotnet new umbraco --name MyProject
      
      - run: git config user.name "Umbraco"
      - run: git config user.email "<bot@umbraco.com>"
      - run: git add .
      - run: git status
      - run: git commit -m "Inital commit of Umbraco"
      - run: git push
      
